language: go
go:
  - 1.12.x
sudo: false
cache:
  directories:
    - $GOCACHE
    - $GOPATH/pkg/mod
env:
  global:
    - GOCACHE=$HOME/.go-build
  matrix:
    - RACE=true
    - ITEST=true
#    - COVER=true

install:
  - go get -v github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - export GO111MODULE=on
  - go build
  - golangci-lint run --build-tags rpctest --disable-all --deadline=10m
      --enable=gofmt
      --enable=vet
      --enable=gosimple
      --enable=unconvert
      --enable=ineffassign

  # Run unit tests with race condition detector.
  - 'if [ "$RACE" = true ]; then make travis-race ; fi'

  # Run integration tests.
  - 'if [ "$ITEST" = true ]; then make itest; fi'

  # Run unit tests and generate coverage report.
  - 'if [ "$COVER" = true ]; then make travis-cover; fi'

after_script:
  - echo "Uploading to termbin.com..."
  - find *.log | xargs -I{} sh -c "cat {} | nc termbin.com 9999 | xargs -r0 printf '{} uploaded to %s'"
  - echo "Uploading to file.io..."
  - tar -zcvO *.log | curl -s -F 'file=@-;filename=logs.tar.gz' https://file.io | xargs -r0 printf 'logs.tar.gz uploaded to %s\n'
